### ISSUE TITLE
An error occurred while loading the image.

### ISSUE THREAD

**Issue by jonmalave** [richardgirges/express-fileupload#349] opened 2023-05-30 09:36 UTC
I can upload a .jpeg just fine, although when I try to open the image uploaded, it seems to become corrupted during the upload process.

See screenshot below. You can see the image file being logged and it looks perfectly normal. I can't figure out what's going wrong, any tips here would be soo appreciated! [🥺](https://emojipedia.org/pleading-face/)[🙏](https://emojipedia.org/folded-hands/) 

![image](https://github.com/richardgirges/express-fileupload/assets/3487527/340b87ee-29c7-4045-8668-6dbd1510bca1)

**Comment by RomanBurunkov** [comment] 2023-09-26 14:07
Hi, are all images affected or only this one?

**Comment by RomanBurunkov** [comment] 2023-11-24 20:32
I'm closing this issue since can't reproduce it and there is no further updates from the issue reporter.
Feel free to re-open it if any new details or step to reproduce will be available.

**Closed by RomanBurunkov** 2023-11-24 20:32 UTC
