### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by simerjit-fwrk** [richardgirges/express-fileupload#29] opened 2017-05-19 06:14 UTC
Error:
```
node_work/node_modules/express-fileupload/lib/index.js:3
const Busboy = require('busboy');
^^^^^
SyntaxError: Use of const in strict mode.
```

I am getting this error. If I replace constant with var then it gives new error 
```
node_work/node_modules/express-fileupload/lib/index.js:35
  let busboyOptions = {};
  ^^^
SyntaxError: Unexpected strict mode reserved word
```

**Comment by dhyey35** [comment] 2017-05-19 10:53
Can you please let us know the nodejs version you are using ?

**Comment by simerjit-fwrk** [comment] 2017-05-22 05:10
@dhyey35 node version is 6.9.1

**Comment by richardgirges** [comment] 2017-05-22 20:27
@simerjit-fwrk thank you for the report. This one is a doozy, let me try running some tests and I will report back with a fix (hopefully). If you happen to know what may be causing the issue, pull requests are always welcome! Otherwise, we'll get this sorted. Cheers.

**Comment by richardgirges** [comment] 2018-01-24 19:37
Still unable to reproduce this. We've made a couple updates to avoid certain ES syntaxes in older versions of Node. Please let me know if the latest version of this package is yielding the same issues. Closing in the meantime.

**Closed by richardgirges** 2018-01-24 19:37 UTC
Labels: help wanted
