### ISSUE TITLE
always no file uploaded

### ISSUE THREAD

**Issue by Mdhaker** [richardgirges/express-fileupload#63] opened 2017-12-20 13:28 UTC
I tested the sample code in the readm page but also didn't work ! i test it with postman and req.files always undifined ! 
how to test it with post man ?
![image](https://user-images.githubusercontent.com/22690712/34209354-0eeae632-e592-11e7-8437-2f9c09104a15.png)

**Comment by muhshahabipour** [comment] 2018-01-06 13:23
remove content-type from headers and test

**Comment by karan-kapoor90** [comment] 2018-01-08 10:15
Same even if no headers are passed.

**Comment by karan-kapoor90** [comment] 2018-01-08 10:20
My bad.. I hadn't loaded the middleware.. 
For anyone else that might be making the stupid mistake I did, dont forget to add
`app.use(fileUpload());`

**Comment by richardgirges** [comment] 2018-01-24 19:57
@Mdhaker there's an issue with certain headers that don't get supported by express-fileupload as expected (such as multipart I believe).

This issue is a duplicate of #31 and will be addressed soon

**Closed by richardgirges** 2018-01-24 19:57 UTC
