### ISSUE TITLE
mv function not working but also not giving error

### ISSUE THREAD

**Issue by 24thdiv** [richardgirges/express-fileupload#54] opened 2017-11-03 23:25 UTC
Hi,
I am uploading image file. I am getting file in my server side. but when i execute 'mv' function it's not uploading my file to given destination and its also not giving me any error.

my server side code.

```
 var pic = req.files.profile_pic;
  var fileName = user_id + '.jpg';
  var newpath = "../public/images/" + fileName;
pic.mv(newpath,function (err) {
            if(err){
                console.log(err);
            }
            else{
                console.log("File uploaded");
            }
        })
```

it prints file uploaded but file is not on given location 'newpath';

**Comment by blavejr** [comment] 2017-11-30 11:49
@24thdiv Same issue here, did you find a fix?

**Comment by blavejr** [comment] 2017-11-30 11:58
@24thdiv I think I found my problem, turns out express-fileupload will not create a new folder, you need to create the folder.

**Comment by 24thdiv** [comment] 2017-12-04 04:46
@blavejr it's still not working.  I already have a folder.   The "mv" function executes successfully but file never uploaded to give folder. Will the be any issue with express version?

**Comment by blavejr** [comment] 2017-12-04 12:43
"var newpath = "../public/images/" + fileName;"
I think your problem is here, fileupload doesn't seem to use relative paths, try and use an absolute path to the file you want to save the images in.
something like ./public/images/" + fileName;

the difference is the . at the beginning.
.. - relative path
. - absolute path.

Hope that helps mate, it worked for me.

**Comment by Muneem** [comment] 2017-12-24 06:34
i am also facing same issue. I have tried absolute path also but no luck

**Comment by richardgirges** [comment] 2018-01-24 19:49
For those of you experiencing the issue, would you mind showing some additional code:

* Where you instantiate express-fileupload (i.e. your `app.use()`)
* The full example of your usage of `.mv()`

I am having a hard time reproducing this, but my guess is that there's some sort of edge case (maybe what @blavejr is mentioning with relative vs absolute paths) that's causing this problem.

**Comment by haoranzhang929** [comment] 2018-02-16 22:13
I had the same issue. But after trying @blavejr 's solution: create the folder I want to put my file into and change my path from relative path to absolute path, It works perfectly now. Thanks!

**Comment by itsgracian** [comment] 2018-10-05 08:32
> I had the same issue. But after trying @blavejr 's solution: create the folder I want to put my file into and change my path from relative path to absolute path, It works perfectly now. Thanks!

please can you show me example of how you did it.. for me it does not work. thanks.

**Comment by itsgracian** [comment] 2018-10-05 08:46
oooh it works .... thanks...

**Comment by richardgirges** [comment] 2018-10-18 15:17
An enhancement that could help alleviate this issue is to add some sort of "create the directory if doesn't exist" logic to `mv()`. This could be an argument passed into the `mv()` method itself, or as a global `express-fileupload` option. 

Need to think about it some more, but I'll keep this ticket open to serve as a reminder for this potential enhancement.

**Comment by Mritunjay10** [comment] 2018-12-12 13:32
sampleFile.mv(path.dirname(require.main.filename)+'/public/uploads/users/CSELL_'
            +operations.randomNumber(4)+"_"+moment().valueOf()+extension, (err)=> {
            
            if(!err)
                fileUploadStatus=true;
        });
No value is assigned to fileUploadStatus

**Comment by RomanBurunkov** [comment] 2019-03-11 05:59
mv function now creates parent path if option 'createParentPath' set, see documentations.

**Closed by RomanBurunkov** 2019-03-11 05:59 UTC
Labels: enhancement

**Comment by aa947** [comment] 2020-02-10 15:52
I have the same issue, solved by adding the public to the path.
and if you start with __dirname make sure to navigate to the specific folder.
because __dirname here points to this folder, not the root folder

**Comment by asadalien** [comment] 2020-03-22 07:47
> @blavejr it's still not working. I already have a folder. The "mv" function executes successfully but file never uploaded to give folder. Will the be any issue with express version?

not working directories are created but still image is not moving to the directory

**Comment by mechaOwl** [comment] 2020-07-23 00:23
```
newpath = "../public/images/" + fileName;

pic.mv(newpath,function (err) {
            if(err){
                console.log(err);
            }
            else{
                console.log("File uploaded");
            }
})
```

I had a same issue where the file was not moved to the newpath, but also did not hit the error condition.

I believe the problem is with appending the name in the move destination 'newpath'.  You should just name the directory you want to move the file to.  I made this mistake as well.  I'm not sure what the proper way to rename the file is.  It may be worth considering as an "issue" that 'mv' in Linux allows you to rename the file as well. 

Side note: paths that start with './' are relative paths, they are relative to the current directory.  Absolute paths begin with '/', but this should be besides the issue.

I hope people find this helpful.

**Comment by mohdhaider07** [comment] 2022-02-23 05:22
I am trying to move the image in folder but the error comes
i give the code given bellow.

image.mv is not a function

 let image = req.body.sampleFile;
 let uploadPath=__dirname+"/public/post-images/"+image;
 image.mv(uploadPath,function(err){
    if(err) console.log(err);
 });

**Comment by navkc11** [comment] 2022-07-26 16:49
hello i have similar problem this create the file in folder, but the file is empty. this what i am write:
file.mv(./${filePath})

**Comment by Klux32** [comment] 2022-07-27 08:56
for me it works  locally. but in production image is never uploaded... what should I do?
