### ISSUE TITLE
.webp upload issues

### ISSUE THREAD

**Issue by russoedu** [richardgirges/express-fileupload#225] opened 2020-06-17 20:01 UTC
Hi,

when uploading .webp files, it looks like the extension changes and this ends up making all the next steps failing

```
{
  name: '02w.ebp',
  data: <Buffer >,
  size: 12110,
  encoding: '7bit',
  tempFilePath: 'favicon-tmp\\tmp-1-1592422602012',
  truncated: false,
  mimetype: 'image/webp',
  md5: 'b588463ef01d94d1636a8378c8c3d8b5',
  mv: [Function: mv]
}
```

The original file name was "02.webp".

If I try to manipulate the file, I receive an Error: EBUSY message.

With other file formats (bmp, svg, png, gif, jpg) all works

Even with "jpeg", even the same happens, the manipulation after the upload works

```
{
  name: '02j.peg',
  data: <Buffer >,
  size: 16833,
  encoding: '7bit',
  tempFilePath: 'favicon-tmp\\tmp-1-1592424047154',
  truncated: false,
  mimetype: 'image/jpeg',
  md5: 'c502247aaebf271d38bbba3b9f19d0c4',
  mv: [Function: mv]
}
```

**Comment by russoedu** [comment] 2020-06-19 06:09
Apparently it's a general issue with uploading .webp files. The same issue happens with multer. The file is uploaded and stays "open"

**Comment by RomanBurunkov** [comment] 2020-06-25 13:55
About the extension cutting.
Do you use safeFileNames option?

**Comment by RomanBurunkov** [comment] 2020-06-26 11:25
Have just tried to upload webp file.
Works ok for me, no issues.

```
Express-file-upload: Temporary file path is /projects/express-fileupload-project/temp/tmp-6-1593170454630
Express-file-upload: New upload started sampleFile->webptest.webp, bytes:0
Express-file-upload: Opening write stream for sampleFile->webptest.webp...
Express-file-upload: Uploading sampleFile->webptest.webp, bytes:13885...
Express-file-upload: Uploading sampleFile->webptest.webp, bytes:39202...
Express-file-upload: Temporary file path is /projects/express-fileupload-project/temp/tmp-8-1593170454631
Express-file-upload: New upload started sampleFile1->tmp-7-1593170454631, bytes:0
Express-file-upload: Temporary file path is /projects/express-fileupload-project/temp/tmp-10-1593170454632
Express-file-upload: New upload started sampleFile2->tmp-9-1593170454632, bytes:0
Express-file-upload: Upload finished sampleFile->webptest.webp, bytes:39202
Express-file-upload: Upload sampleFile->webptest.webp completed, bytes:39202.
Express-file-upload: Upload finished sampleFile1->tmp-7-1593170454631, bytes:0
Express-file-upload: Upload finished sampleFile2->tmp-9-1593170454632, bytes:0
req.files >>> {
  sampleFile: {
    name: 'webptest.webp',
    data: <Buffer >,
    size: 39202,
    encoding: '7bit',
    tempFilePath: '/projects/express-fileupload-project/temp/tmp-6-1593170454630',
    truncated: false,
    mimetype: 'image/webp',
    md5: 'e4b3492b902530ea0eb45e36d9df4be8',
    mv: [Function: mv]
  }
}
Express-file-upload: Moving temporary file /projects/express-fileupload-project/temp/tmp-6-1593170454630 to /projects/express-fileupload-project/uploads/webptest.webp

```

@russoedu  I need more details about what version and software you have and also steps on how to reproduce it.
Also keep in mind option I've mentioned in my previous update.

**Comment by russoedu** [comment] 2020-06-26 11:54
> About the extension cutting.
> Do you use safeFileNames option?

I'm not. I'll try with it.

> Have just tried to upload webp file.
> Works ok for me, no issues.
> @russoedu I need more details about what version and software you have and also steps on how to reproduce it.
> Also keep in mind option I've mentioned in my previous update.

The upload happens normally, but if I try to rename or do any "fs" manipulation, it fails saying the file is busy.

I made an attempt with Multer and the same happened. Not sure if it's an issue with Busboy (both use it). If I stop the service and try to manipulate the file, it works normally - so, the file has been uploaded completely, but something is keeping it locked.

I even tried putting the whole process in a try-catch loop with 500ms waiting time to see if somehow the upload was finishing, but it's not the case, something is locking the file for good.

**Comment by RomanBurunkov** [comment] 2020-07-16 10:21
Hi @russoedu  have you figure out what cause the issue?
Is it related to the express-fileupload? 

I was not able to reproduce any of described issues.

**Comment by RomanBurunkov** [comment] 2020-07-20 07:14
Closing since couldn't reproduce that and didn't get response from the topic starter.

**Closed by RomanBurunkov** 2020-07-20 07:14 UTC
Labels: needs info

**Comment by Notice-Jeroen-Meijer** [comment] 2020-07-24 09:22
I have what I guess is the same issue (but different?). Environment (which I believe is unrelated, but not extensively checked): docker on ubuntu.

When I upload a json file with `{ safeFileNames: true, createParentPath: true, preserveExtension: true }` the file ends up being uploaded as xxxxj.son instead of xxxx.json. My conclusion is was that preserveExtension simply assumes the extension is three characters, but that is probably a bit of a naive theory.

Let me know if you prefer a new issue, or need more info.
