### ISSUE TITLE
express-fileupload

### ISSUE THREAD

**Issue by sinchi** [richardgirges/express-fileupload#1] opened 2015-10-21 08:58 UTC
Hello
i have an issue with express-fileupload  module when i upload the file , i receive a empty file with 0 octet !!

**Comment by richardgirges** [comment] 2016-03-13 03:55
@sinchi can you provide steps on how I can reproduce this issue?

**Comment by richardgirges** [comment] 2016-04-22 20:43
@sinchi still waiting on repro steps. Pushed a couple updates since then. Will close this out; lemme know if the issue still exists and I'll look into it.

**Closed by richardgirges** 2016-04-22 20:43 UTC
